# Umami Analytics Infrastructure
# Self-hosted, privacy-focused web analytics
# 
# This creates:
# 1. PostgreSQL database on Exoscale DBaaS for Umami
# 2. Outputs connection details for Kubernetes deployment

# ============================================
# Umami PostgreSQL Database (Exoscale DBaaS)
# ============================================
resource "exoscale_dbaas" "umami_postgres" {
  count = var.umami_enabled ? 1 : 0
  
  zone = var.zone
  name = "${var.project_name}-umami-${var.environment}"
  type = "pg"
  plan = var.umami_postgres_plan
  
  termination_protection = false  # Disable to allow deletion

  pg {
    admin_username  = var.umami_db_user
    admin_password  = var.umami_db_password
    # Allow all IPs - Kubernetes pods need access
    ip_filter       = ["0.0.0.0/0"]
    backup_schedule = "04:00"  # Daily backup at 4 AM UTC
    version         = "15"     # PostgreSQL 15
  }
}

# Data source to get Umami PostgreSQL connection URI
data "exoscale_database_uri" "umami_postgres_uri" {
  count = var.umami_enabled ? 1 : 0
  
  name = exoscale_dbaas.umami_postgres[0].name
  zone = var.zone
  type = "pg"
}

# ============================================
# Outputs
# ============================================
output "umami_postgres_uri" {
  description = "Umami PostgreSQL database connection URI"
  value       = var.umami_enabled ? data.exoscale_database_uri.umami_postgres_uri[0].uri : null
  sensitive   = true
}

output "umami_postgres_host" {
  description = "Umami PostgreSQL database host"
  value       = var.umami_enabled ? exoscale_dbaas.umami_postgres[0].name : null
}

output "umami_database_name" {
  description = "Umami database name"
  value       = var.umami_enabled ? "${var.project_name}-umami-${var.environment}" : null
}

# ============================================
# Local file for Kubernetes secrets
# ============================================
resource "local_file" "umami_k8s_secrets" {
  count    = var.umami_enabled ? 1 : 0
  filename = "${path.module}/../k8s/manifests/umami-secrets.yaml"
  # Modify the database URL to skip certificate verification (Exoscale DBaaS uses self-signed certs)
  content  = <<-EOF
    # Auto-generated by Terraform - DO NOT EDIT
    # To regenerate: cd terraform && terraform apply
    apiVersion: v1
    kind: Secret
    metadata:
      name: umami-secrets
      namespace: umami
    type: Opaque
    stringData:
      database-url: "${replace(data.exoscale_database_uri.umami_postgres_uri[0].uri, "sslmode=require", "sslmode=no-verify")}"
      app-secret: "${var.umami_app_secret}"
  EOF
}

