
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const AdminAnalyticsPage = lazy(() => import("./pages/AdminAnalyticsPage.tsx"));
const AdminApprovedDocumentsPage = lazy(() => import("./pages/AdminApprovedDocumentsPage.tsx"));
const AdminBannedTagsPage = lazy(() => import("./pages/AdminBannedTagsPage.tsx"));
const AdminBannedWordsPage = lazy(() => import("./pages/AdminBannedWordsPage.tsx"));
const AdminCommentModerationPage = lazy(() => import("./pages/AdminCommentModerationPage.tsx"));
const AdminDashboardPage = lazy(() => import("./pages/AdminDashboardPage.tsx"));
const AdminDocumentEditPage = lazy(() => import("./pages/AdminDocumentEditPage.tsx"));
const AdminLoginPage = lazy(() => import("./pages/AdminLoginPage.tsx"));
const AdminManagementPage = lazy(() => import("./pages/AdminManagementPage.tsx"));
const AdminPendingDocumentsPage = lazy(() => import("./pages/AdminPendingDocumentsPage.tsx"));
const AdminTranslationsPage = lazy(() => import("./pages/AdminTranslationsPage.tsx"));
const AdminTopViewedPage = lazy(() => import("./pages/AdminTopViewedPage.tsx"));
const AboutPage = lazy(() => import("./pages/AboutPage.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const DisclaimerPage = lazy(() => import("./pages/DisclaimerPage.tsx"));
const DocumentDetailPage = lazy(() => import("./pages/DocumentDetailPage.tsx"));
const FOIPage = lazy(() => import("./pages/FOIPage.tsx"));
const PrivacyGuaranteedPage = lazy(() => import("./pages/PrivacyGuaranteedPage.tsx"));
const SearchPage = lazy(() => import("./pages/SearchPage.tsx"));
const UploadDocumentPage = lazy(() => import("./pages/UploadDocumentPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/admin-analytics-page", element: <AdminAnalyticsPage />},
	{ path: "/adminanalyticspage", element: <AdminAnalyticsPage />},
	{ path: "/admin-approved-documents-page", element: <AdminApprovedDocumentsPage />},
	{ path: "/adminapproveddocumentspage", element: <AdminApprovedDocumentsPage />},
	{ path: "/admin-banned-tags-page", element: <AdminBannedTagsPage />},
	{ path: "/adminbannedtagspage", element: <AdminBannedTagsPage />},
	{ path: "/admin-banned-words-page", element: <AdminBannedWordsPage />},
	{ path: "/adminbannedwordspage", element: <AdminBannedWordsPage />},
	{ path: "/admin-comment-moderation-page", element: <AdminCommentModerationPage />},
	{ path: "/admincommentmoderationpage", element: <AdminCommentModerationPage />},
	{ path: "/admin-dashboard-page", element: <AdminDashboardPage />},
	{ path: "/admindashboardpage", element: <AdminDashboardPage />},
	{ path: "/admin-document-edit-page", element: <AdminDocumentEditPage />},
	{ path: "/admindocumenteditpage", element: <AdminDocumentEditPage />},
	{ path: "/admin-login-page", element: <AdminLoginPage />},
	{ path: "/adminloginpage", element: <AdminLoginPage />},
	{ path: "/admin-management-page", element: <AdminManagementPage />},
	{ path: "/adminmanagementpage", element: <AdminManagementPage />},
	{ path: "/admin-pending-documents-page", element: <AdminPendingDocumentsPage />},
	{ path: "/adminpendingdocumentspage", element: <AdminPendingDocumentsPage />},
	{ path: "/admin-translations-page", element: <AdminTranslationsPage />},
	{ path: "/admintranslationspage", element: <AdminTranslationsPage />},
	{ path: "/admin-top-viewed-page", element: <AdminTopViewedPage />},
	{ path: "/admintopviewedpage", element: <AdminTopViewedPage />},
	{ path: "/about", element: <AboutPage />},
	{ path: "/aboutpage", element: <AboutPage />},
	{ path: "/", element: <App />},
	{ path: "/disclaimer", element: <DisclaimerPage />},
	{ path: "/disclaimerpage", element: <DisclaimerPage />},
	{ path: "/document/:id", element: <DocumentDetailPage />},
	{ path: "/document-detail-page", element: <DocumentDetailPage />},
	{ path: "/documentdetailpage", element: <DocumentDetailPage />},
	{ path: "/foi", element: <FOIPage />},
	{ path: "/foipage", element: <FOIPage />},
	{ path: "/privacy-guaranteed-page", element: <PrivacyGuaranteedPage />},
	{ path: "/privacyguaranteedpage", element: <PrivacyGuaranteedPage />},
	{ path: "/search-page", element: <SearchPage />},
	{ path: "/searchpage", element: <SearchPage />},
	{ path: "/upload-document-page", element: <UploadDocumentPage />},
	{ path: "/uploaddocumentpage", element: <UploadDocumentPage />},

];
