#!/bin/bash

# Setup Umami Analytics for HaqNow
# This script deploys Umami using Terraform + Kubernetes

set -e

echo "🔍 Setting up Umami Analytics..."

# Check prerequisites
check_prerequisites() {
    echo "📋 Checking prerequisites..."
    
    if ! command -v terraform &> /dev/null; then
        echo "❌ Terraform is not installed. Please install Terraform first."
        exit 1
    fi
    
    if ! command -v kubectl &> /dev/null; then
        echo "❌ kubectl is not installed. Please install kubectl first."
        exit 1
    fi
    
    echo "✅ Prerequisites met"
}

# Generate secure credentials if not set
generate_credentials() {
    echo "🔐 Checking Umami credentials..."
    
    cd "$(dirname "$0")/../terraform"
    
    # Check if credentials are set in terraform.tfvars
    if grep -q "REPLACE_WITH_SECURE_PASSWORD" terraform.tfvars; then
        echo "⚠️  Umami credentials not set in terraform.tfvars"
        echo ""
        echo "Please update terraform/terraform.tfvars with secure values:"
        echo ""
        echo "  umami_db_password = \"$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)\""
        echo "  umami_app_secret  = \"$(openssl rand -hex 32)\""
        echo ""
        echo "Then re-run this script."
        exit 1
    fi
    
    echo "✅ Credentials configured"
    cd - > /dev/null
}

# Deploy infrastructure with Terraform
deploy_terraform() {
    echo "🏗️  Deploying Umami infrastructure with Terraform..."
    
    cd "$(dirname "$0")/../terraform"
    
    terraform init -upgrade
    terraform plan -target=exoscale_dbaas.umami_postgres -target=local_file.umami_k8s_secrets
    
    echo ""
    read -p "Apply Terraform changes? (y/n) " -n 1 -r
    echo ""
    
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        terraform apply -target=exoscale_dbaas.umami_postgres -target=local_file.umami_k8s_secrets -auto-approve
        echo "✅ Terraform infrastructure deployed"
    else
        echo "❌ Terraform apply cancelled"
        exit 1
    fi
    
    cd - > /dev/null
}

# Deploy to Kubernetes
deploy_kubernetes() {
    echo "☸️  Deploying Umami to Kubernetes..."
    
    # Set kubeconfig
    export KUBECONFIG="${KUBECONFIG:-$(pwd)/k8s/.kubeconfig}"
    
    if ! kubectl cluster-info > /dev/null 2>&1; then
        echo "❌ Cannot connect to Kubernetes cluster"
        echo "   Make sure KUBECONFIG is set correctly"
        exit 1
    fi
    
    # Apply secrets (generated by Terraform)
    if [ -f "k8s/manifests/umami-secrets.yaml" ]; then
        kubectl apply -f k8s/manifests/umami-secrets.yaml
        echo "✅ Secrets applied"
    else
        echo "❌ umami-secrets.yaml not found"
        echo "   Run 'terraform apply' first to generate secrets"
        exit 1
    fi
    
    # Apply deployment
    kubectl apply -f k8s/manifests/umami-deployment.yaml
    echo "✅ Deployment applied"
    
    # Wait for rollout
    echo "⏳ Waiting for Umami to be ready..."
    kubectl rollout status deployment/umami -n umami --timeout=120s
}

# Check deployment health
check_health() {
    echo "🔍 Checking Umami health..."
    
    export KUBECONFIG="${KUBECONFIG:-$(pwd)/k8s/.kubeconfig}"
    
    # Get pod status
    kubectl get pods -n umami
    
    # Check if pod is running
    POD_STATUS=$(kubectl get pods -n umami -l app=umami -o jsonpath='{.items[0].status.phase}' 2>/dev/null || echo "NotFound")
    
    if [ "$POD_STATUS" = "Running" ]; then
        echo ""
        echo "============================================"
        echo "✅ Umami Analytics Setup Complete!"
        echo "============================================"
        echo ""
        echo "🌐 Access Umami at: https://analytics.haqnow.com"
        echo "   (After DNS is configured)"
        echo ""
        echo "🔑 Default credentials:"
        echo "   Username: admin"
        echo "   Password: umami"
        echo ""
        echo "⚠️  IMPORTANT: Change the default password immediately!"
        echo ""
        echo "📋 Next steps:"
        echo "   1. Configure DNS: analytics.haqnow.com → SKS NLB IP"
        echo "   2. Login to Umami and change password"
        echo "   3. Add website: www.haqnow.com"
        echo "   4. Copy website ID"
        echo "   5. Update frontend/index.html with website ID"
        echo "   6. Deploy: ./scripts/deploy.sh patch"
        echo ""
    else
        echo "❌ Umami pod is not running (status: $POD_STATUS)"
        echo "   Check logs: kubectl logs -n umami -l app=umami"
        exit 1
    fi
}

# Main execution
main() {
    check_prerequisites
    generate_credentials
    deploy_terraform
    deploy_kubernetes
    check_health
}

main "$@"
